name: Build 2pdownloader

on:
  workflow_dispatch:

jobs:
  build-windows:
    strategy:
      matrix:
        architecture: [x86_64, arm64]
    runs-on: windows-2019
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --timeout=300 -r requirements.txt

      - name: Build with Nuitka
        run: |
          python -c "from app.common.config import VERSION; f = open('version.txt', 'w'); f.write(VERSION); f.close()"
          $VERSION = gc version.txt
          Write-Host "VERSION=$VERSION"
          echo "VERSION=$VERSION" >> $env:GITHUB_ENV
          del version.txt
          python deploy.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: 2pdownloader-v${{ env.VERSION }}-Windows-${{ matrix.architecture }}
          path: dist/2pdownloader.dist

  build-macos:
    strategy:
      matrix:
        architecture: [arm64, x86_64]
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --timeout=300 -r requirements.txt

      - name: Build with Nuitka
        run: |
          python3 -c "import sys; sys.path.append('./app/common'); import config; print(config.VERSION)" > version.txt
          version=$(sed -n '4p' version.txt)
          echo "VERSION=${version}" >> "$GITHUB_ENV"
          rm -rf version.txt
          python3 deploy.py
          chmod u+x "dist/2pdownloader.app/Contents/MacOS/2pdownloader"
          rm -rf "dist/2pdownloader.build"
          rm -rf "dist/2pdownloader.dist"
          mv "dist/2pdownloader.app" "dist/2pdownloader.app"

      - name: Create DMG
        run: |
          ln -s /Applications dist/Applications
          sleep 1
          hdiutil create -srcfolder "dist/" -volname "2pdownloader" -fs HFS+ -fsargs "-c c=64,a=16,e=16" -format UDZO -size 400m "2pdownloader-v${{ env.VERSION }}-macOS-${{ matrix.architecture }}.dmg"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: 2pdownloader-v${{ env.VERSION }}-macOS-${{ matrix.architecture }}
          path: 2pdownloader-v${{ env.VERSION }}-macOS-${{ matrix.architecture }}.dmg

  build-ubuntu:
    strategy:
      matrix:
        architecture: [x86_64, arm64]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libegl1-mesa
          pip install --timeout=300 -r requirements.txt

      - name: Build with Nuitka
        run: |
          python3 -c "import sys; sys.path.append('./app/common'); import config; print(config.VERSION)" > version.txt
          version=$(sed -n '4p' version.txt)
          echo "VERSION=${version}" >> "$GITHUB_ENV"
          rm -rf version.txt
          python deploy.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: 2pdownloader-v${{ env.VERSION }}-Linux-${{ matrix.architecture }}
          path: dist/2pdownloader.dist
